/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#494bd6",
        "primary-container": "#6063ee",
        "on-secondary-fixed-variant": "#444749",
        "error-container": "#ffdad6",
        "secondary-container": "#e0e3e5",
        "secondary-fixed": "#e0e3e5",
        "on-background": "#151c27",
        "tertiary": "#525d6c",
        "tertiary-fixed": "#d9e3f6",
        "primary-fixed": "#e1e0ff",
        "surface-bright": "#f9f9ff",
        "on-surface-variant": "#464554",
        "surface-container": "#e7eefe",
        "surface": "#f9f9ff",
        "error": "#ba1a1a",
        "on-secondary-container": "#626567",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "on-error": "#ffffff",
        "surface-dim": "#d3daea",
        "tertiary-fixed-dim": "#bdc7d9",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "background": "#f9f9ff",
        "on-secondary-fixed": "#191c1e",
        "secondary": "#5c5f61",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#3d4756",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-highest": "#dce2f3",
        "on-tertiary-fixed": "#121c2a",
        "on-primary-fixed": "#07006c",
        "on-error-container": "#93000a",
        "inverse-primary": "#c0c1ff",
        "inverse-surface": "#2a313d",
        "secondary-fixed-dim": "#c4c7c9",
        "on-surface": "#151c27",
        "on-tertiary-container": "#fdfcff",
        "tertiary-container": "#6b7586",
        "primary": "#4648d4",
        "surface-variant": "#dce2f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e2e8f8",
        "outline-variant": "#c7c4d7",
        "outline": "#767586"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "xs": "4px",
        "md": "16px",
        "lg": "24px",
        "container-max": "1280px",
        "sm": "8px",
        "sidebar-width": "260px",
        "base": "4px",
        "xl": "32px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "title-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
